### ISSUE TITLE
NPE in CloudFoundryAppScheduler#getJobPageCoun() on empty schedulers

### ISSUE THREAD

**Issue by tzolov** [spring-cloud/spring-cloud-scheduler-cloudfoundry#21]
The [CloudFoundryAppScheduler#getJobPageCoun()](https://github.com/spring-cloud/spring-cloud-scheduler-cloudfoundry/blob/master/src/main/java/org/springframework/cloud/scheduler/spi/cloudfoundry/CloudFoundryAppScheduler.java#L296) throws NPE if there are no any schedulers registered.

**Comment by cppwfs** [comment]
@tzolov this error occurs sporadically from the PCF Client.  I can remove all jobs and schedules from the Scheduler and the code works fine.  However from time to time it returns a null.  I'm opening an issue with them.
