### ISSUE TITLE
Move CloudFoundryAppScheduler to CF-deployer

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-scheduler-cloudfoundry#50]

**Comment by ilayaperumalg** [comment]
Issue moved to [spring-cloud/spring-cloud-deployer-cloudfoundry #304](https://github.com/spring-cloud/spring-cloud-deployer-cloudfoundry/issues/304) via [**ZenHub**](https://www.zenhub.com/)
